// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:67826758-3f7b-460b-89c6-a9d9cd4ce228",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_6q9wOWMGm",
    "aws_user_pools_web_client_id": "54mhiu7dk16bf67pm1qj4a0t02",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://xo37ogzwc5dwtkzlgjs7e5r754.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
